//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMYFrameWorkMVC.Common.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRoleSiteMapNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetRoleSiteMapNode()
        {
            this.AspNetRoleSiteMapNodes1 = new HashSet<AspNetRoleSiteMapNode>();
        }
    
        public string ID { get; set; }
        public string AspNetRoleID { get; set; }
        public string NodeKey { get; set; }
        public string ParentID { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRoleSiteMapNode> AspNetRoleSiteMapNodes1 { get; set; }
        public virtual AspNetRoleSiteMapNode AspNetRoleSiteMapNode1 { get; set; }
    }
}
