//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMYFrameWorkMVC.Common.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser_Connections
    {
        public string ID { get; set; }
        public string UserId { get; set; }
        public string ConnectionID { get; set; }
        public string IP { get; set; }
        public string Browser { get; set; }
        public string Version { get; set; }
        public string Type { get; set; }
        public string Platform { get; set; }
        public Nullable<bool> IsMobileDevice { get; set; }
        public string MobileDeviceModel { get; set; }
        public string MobileDeviceManufacturer { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedAt { get; set; }
        public string SessionID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
