//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMYFrameWorkMVC.Common.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBAudit
    {
        public string AuditId { get; set; }
        public string ParentID { get; set; }
        public Nullable<System.DateTime> RevisionStamp { get; set; }
        public string TableName { get; set; }
        public string UserId { get; set; }
        public string Action { get; set; }
        public string JSONData { get; set; }
    }
}
