//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMYFrameWorkMVC.Common.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsFile
    {
        public string ID { get; set; }
        public string SettingID { get; set; }
        public string FileShortPath { get; set; }
        public string FileName { get; set; }
    
        public virtual Setting Setting { get; set; }
    }
}
