//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMYFrameWorkMVC.Common.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckExpens
    {
        public string Id { get; set; }
        public string ExpenseTypeId { get; set; }
        public string TruckId { get; set; }
        public double Price { get; set; }
        public System.DateTime AtDate { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedAt { get; set; }
    
        public virtual TruckExpensType TruckExpensType { get; set; }
        public virtual Truck Truck { get; set; }
    }
}
