//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMYFrameWorkMVC.Common.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckLoad
    {
        public string Id { get; set; }
        public string TruckId { get; set; }
        public string DriverId { get; set; }
        public string CompanyId { get; set; }
        public string StatusId { get; set; }
        public Nullable<int> Milage { get; set; }
        public string FromStateId { get; set; }
        public string ToStateId { get; set; }
        public string FromNotes { get; set; }
        public string ToNotes { get; set; }
        public string Notes { get; set; }
        public double Price { get; set; }
        public double PricePerMile { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public double FuelCost { get; set; }
        public double DriverPerMileCost { get; set; }
        public double DriverCost { get; set; }
        public double OtherCosts { get; set; }
        public string OtherCostsNotes { get; set; }
        public double TotalCosts { get; set; }
        public double TotalIncome { get; set; }
        public double TotalProfit { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedAt { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual TruckLoadStatus TruckLoadStatus { get; set; }
        public virtual Truck Truck { get; set; }
        public virtual USAState USAState { get; set; }
        public virtual USAState USAState1 { get; set; }
    }
}
