//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMYFrameWorkMVC.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMYFrameWorkMVC.Common.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At date.
        /// </summary>
        public static string AtDate {
            get {
                return ResourceManager.GetString("AtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company added successfully.
        /// </summary>
        public static string CompanyAddedSuccessfully {
            get {
                return ResourceManager.GetString("CompanyAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company deleted successfully.
        /// </summary>
        public static string CompanyDeletedSuccessfully {
            get {
                return ResourceManager.GetString("CompanyDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company updated successfully.
        /// </summary>
        public static string CompanyUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("CompanyUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number.
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver added successfully.
        /// </summary>
        public static string DriverAddedSuccessfully {
            get {
                return ResourceManager.GetString("DriverAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver cost.
        /// </summary>
        public static string DriverCost {
            get {
                return ResourceManager.GetString("DriverCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver deleted successfully.
        /// </summary>
        public static string DriverDeletedSuccessfully {
            get {
                return ResourceManager.GetString("DriverDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver per mile cost.
        /// </summary>
        public static string DriverPerMileCost {
            get {
                return ResourceManager.GetString("DriverPerMileCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver updated successfully.
        /// </summary>
        public static string DriverUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("DriverUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration is over lapped with other load.
        /// </summary>
        public static string DurationIsOverLappedWithOtherLoad {
            get {
                return ResourceManager.GetString("DurationIsOverLappedWithOtherLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email  already exists.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter message.
        /// </summary>
        public static string EnterMessage {
            get {
                return ResourceManager.GetString("EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense type.
        /// </summary>
        public static string ExpenseType {
            get {
                return ResourceManager.GetString("ExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From notes.
        /// </summary>
        public static string FromNotes {
            get {
                return ResourceManager.GetString("FromNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From state.
        /// </summary>
        public static string FromState {
            get {
                return ResourceManager.GetString("FromState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From .
        /// </summary>
        public static string FromUser {
            get {
                return ResourceManager.GetString("FromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel cost.
        /// </summary>
        public static string FuelCost {
            get {
                return ResourceManager.GetString("FuelCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load added successfully.
        /// </summary>
        public static string LoadAddedSuccessfully {
            get {
                return ResourceManager.GetString("LoadAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load deleted successfully.
        /// </summary>
        public static string LoadDeletedSuccessfully {
            get {
                return ResourceManager.GetString("LoadDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load updated successfully.
        /// </summary>
        public static string LoadUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("LoadUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login first to complete operation.
        /// </summary>
        public static string LoginFirstToCompleteOperation {
            get {
                return ResourceManager.GetString("LoginFirstToCompleteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sent.
        /// </summary>
        public static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message text.
        /// </summary>
        public static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milage.
        /// </summary>
        public static string Milage {
            get {
                return ResourceManager.GetString("Milage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists.
        /// </summary>
        public static string NameExists {
            get {
                return ResourceManager.GetString("NameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On buy date.
        /// </summary>
        public static string OnBuyDate {
            get {
                return ResourceManager.GetString("OnBuyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On buy expenses.
        /// </summary>
        public static string OnBuyExpenses {
            get {
                return ResourceManager.GetString("OnBuyExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On buy milage.
        /// </summary>
        public static string OnBuyMilage {
            get {
                return ResourceManager.GetString("OnBuyMilage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On buy notes.
        /// </summary>
        public static string OnBuyNotes {
            get {
                return ResourceManager.GetString("OnBuyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On buy price.
        /// </summary>
        public static string OnBuyPrice {
            get {
                return ResourceManager.GetString("OnBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other costs.
        /// </summary>
        public static string OtherCosts {
            get {
                return ResourceManager.GetString("OtherCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other costs notes.
        /// </summary>
        public static string OtherCostsNotes {
            get {
                return ResourceManager.GetString("OtherCostsNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permisions.
        /// </summary>
        public static string Permisions {
            get {
                return ResourceManager.GetString("Permisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number already exists.
        /// </summary>
        public static string PhoneNumberExists {
            get {
                return ResourceManager.GetString("PhoneNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per mile.
        /// </summary>
        public static string PricePerMile {
            get {
                return ResourceManager.GetString("PricePerMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record could not be deleted because there are records related to it .
        /// </summary>
        public static string RefrenceDeleteError {
            get {
                return ResourceManager.GetString("RefrenceDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role added successfully.
        /// </summary>
        public static string RoleAddedSuccessfully {
            get {
                return ResourceManager.GetString("RoleAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role deleted successfully.
        /// </summary>
        public static string RoleDeletedSuccessfully {
            get {
                return ResourceManager.GetString("RoleDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles list.
        /// </summary>
        public static string RolesList {
            get {
                return ResourceManager.GetString("RolesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role updated successfully.
        /// </summary>
        public static string RoleUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("RoleUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting updated successfully.
        /// </summary>
        public static string SettingUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("SettingUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State code.
        /// </summary>
        public static string StateCode {
            get {
                return ResourceManager.GetString("StateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this entity is not deletable because it is part of the system.
        /// </summary>
        public static string ThisIsNotDeletAble {
            get {
                return ResourceManager.GetString("ThisIsNotDeletAble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete the last record .
        /// </summary>
        public static string ThisIsTheLastRecord {
            get {
                return ResourceManager.GetString("ThisIsTheLastRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To notes.
        /// </summary>
        public static string ToNotes {
            get {
                return ResourceManager.GetString("ToNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To state .
        /// </summary>
        public static string ToState {
            get {
                return ResourceManager.GetString("ToState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To state notes.
        /// </summary>
        public static string ToStateNotes {
            get {
                return ResourceManager.GetString("ToStateNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total costs.
        /// </summary>
        public static string TotalCosts {
            get {
                return ResourceManager.GetString("TotalCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total income.
        /// </summary>
        public static string TotalIncome {
            get {
                return ResourceManager.GetString("TotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total profit.
        /// </summary>
        public static string TotalProfit {
            get {
                return ResourceManager.GetString("TotalProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string ToUser {
            get {
                return ResourceManager.GetString("ToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To users.
        /// </summary>
        public static string ToUsers {
            get {
                return ResourceManager.GetString("ToUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        public static string Truck {
            get {
                return ResourceManager.GetString("Truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck added successfully.
        /// </summary>
        public static string TruckAddedSuccessfully {
            get {
                return ResourceManager.GetString("TruckAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck deleted successfully.
        /// </summary>
        public static string TruckDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TruckDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck expense added successfully.
        /// </summary>
        public static string TruckExpenseAddedSuccessfully {
            get {
                return ResourceManager.GetString("TruckExpenseAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck expense deleted successfully.
        /// </summary>
        public static string TruckExpenseDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TruckExpenseDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck expense updated successfully.
        /// </summary>
        public static string TruckExpenseUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TruckExpenseUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks.
        /// </summary>
        public static string Trucks {
            get {
                return ResourceManager.GetString("Trucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck updated successfully.
        /// </summary>
        public static string TruckUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TruckUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State added successfully.
        /// </summary>
        public static string USAStateAddedSuccessfully {
            get {
                return ResourceManager.GetString("USAStateAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State deleted successfully.
        /// </summary>
        public static string USAStateDeletedSuccessfully {
            get {
                return ResourceManager.GetString("USAStateDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State updated successfully.
        /// </summary>
        public static string USAStateUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("USAStateUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added successfully.
        /// </summary>
        public static string UserAddedSuccessfully {
            get {
                return ResourceManager.GetString("UserAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully.
        /// </summary>
        public static string UserDeletedSuccessfully {
            get {
                return ResourceManager.GetString("UserDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name  already exists.
        /// </summary>
        public static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string UserPasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("UserPasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully.
        /// </summary>
        public static string UserUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UserUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a number..
        /// </summary>
        public static string ValidateNumber {
            get {
                return ResourceManager.GetString("ValidateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} file type must be one of the following ({1}).
        /// </summary>
        public static string ValidationAllowedFileTypes {
            get {
                return ResourceManager.GetString("ValidationAllowedFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be a date.
        /// </summary>
        public static string ValidationDate {
            get {
                return ResourceManager.GetString("ValidationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid e-mail address..
        /// </summary>
        public static string ValidationInvalidEmail {
            get {
                return ResourceManager.GetString("ValidationInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} file size exceeds the allowed size must be less than ({1} bytes).
        /// </summary>
        public static string ValidationMaxFileSize {
            get {
                return ResourceManager.GetString("ValidationMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} character number must be less than {1}..
        /// </summary>
        public static string ValidationMaxLength {
            get {
                return ResourceManager.GetString("ValidationMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {1} characters long..
        /// </summary>
        public static string ValidationMinimumLength {
            get {
                return ResourceManager.GetString("ValidationMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ValidationNotMatch {
            get {
                return ResourceManager.GetString("ValidationNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be numbers only.
        /// </summary>
        public static string ValidationNumber {
            get {
                return ResourceManager.GetString("ValidationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be in past only..
        /// </summary>
        public static string ValidationPastDate {
            get {
                return ResourceManager.GetString("ValidationPastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be from {1} to {2}.
        /// </summary>
        public static string ValidationRange {
            get {
                return ResourceManager.GetString("ValidationRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be valid.
        /// </summary>
        public static string ValidationRegEx {
            get {
                return ResourceManager.GetString("ValidationRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password.
        /// </summary>
        public static string WrongUserNameOrPassword {
            get {
                return ResourceManager.GetString("WrongUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
