//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic name.
        /// </summary>
        internal static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this ?.
        /// </summary>
        internal static string AreYouSureYouWantToDeleteThis {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied 1 rows to clipboard.
        /// </summary>
        internal static string CopyToClipboard_Copied1Rows {
            get {
                return ResourceManager.GetString("CopyToClipboard_Copied1Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied %d rows to clipboard .
        /// </summary>
        internal static string CopyToClipboard_CopiedNRows {
            get {
                return ResourceManager.GetString("CopyToClipboard_CopiedNRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        internal static string CSV {
            get {
                return ResourceManager.GetString("CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available in table.
        /// </summary>
        internal static string DataTable_emptyTable {
            get {
                return ResourceManager.GetString("DataTable_emptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string DataTable_first {
            get {
                return ResourceManager.GetString("DataTable_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ entries.
        /// </summary>
        internal static string DataTable_info {
            get {
                return ResourceManager.GetString("DataTable_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 entries.
        /// </summary>
        internal static string DataTable_infoEmpty {
            get {
                return ResourceManager.GetString("DataTable_infoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ total entries).
        /// </summary>
        internal static string DataTable_infoFiltered {
            get {
                return ResourceManager.GetString("DataTable_infoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string DataTable_last {
            get {
                return ResourceManager.GetString("DataTable_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ entries.
        /// </summary>
        internal static string DataTable_lengthMenu {
            get {
                return ResourceManager.GetString("DataTable_lengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataTable_loadingRecords {
            get {
                return ResourceManager.GetString("DataTable_loadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string DataTable_next {
            get {
                return ResourceManager.GetString("DataTable_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string DataTable_previous {
            get {
                return ResourceManager.GetString("DataTable_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string DataTable_search {
            get {
                return ResourceManager.GetString("DataTable_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        internal static string DataTable_zeroRecords {
            get {
                return ResourceManager.GetString("DataTable_zeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete ?.
        /// </summary>
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTR.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers.
        /// </summary>
        internal static string Drivers {
            get {
                return ResourceManager.GetString("Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user name and password .
        /// </summary>
        internal static string EnterUserNameAndPassword {
            get {
                return ResourceManager.GetString("EnterUserNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        internal static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved {year}.
        /// </summary>
        internal static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error .
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files with types {types}.
        /// </summary>
        internal static string InvalidFileTypeMessage {
            get {
                return ResourceManager.GetString("InvalidFileTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript is not enabled.
        /// </summary>
        internal static string JavaScriptNotEnabled {
            get {
                return ResourceManager.GetString("JavaScriptNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more.
        /// </summary>
        internal static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You exceeded the allowen number of uploads.
        /// </summary>
        internal static string MaxFilesExceeded {
            get {
                return ResourceManager.GetString("MaxFilesExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new messages.
        /// </summary>
        internal static string NewMessages {
            get {
                return ResourceManager.GetString("NewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized.
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar-Jo.
        /// </summary>
        internal static string OtherLang {
            get {
                return ResourceManager.GetString("OtherLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        internal static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        internal static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles list.
        /// </summary>
        internal static string RolesList {
            get {
                return ResourceManager.GetString("RolesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send new message.
        /// </summary>
        internal static string SendNewMessage {
            get {
                return ResourceManager.GetString("SendNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال رسالة جديدة.
        /// </summary>
        internal static string SendNewMessage1 {
            get {
                return ResourceManager.GetString("SendNewMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings list.
        /// </summary>
        internal static string SettingsList {
            get {
                return ResourceManager.GetString("SettingsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management System.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users List.
        /// </summary>
        internal static string UsersList {
            get {
                return ResourceManager.GetString("UsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view all.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email or password .
        /// </summary>
        internal static string WrongEmailOrPassword {
            get {
                return ResourceManager.GetString("WrongEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        internal static string YouHave {
            get {
                return ResourceManager.GetString("YouHave", resourceCulture);
            }
        }
    }
}
